### ISSUE TITLE
Unexpected behaviour on mobile devices 

### ISSUE THREAD

**Issue by louieogrady** [willmendesneto/ngx-scroll-lock#22]
**I'm submitting a ...** (check one with "x")

- [x ] bug report => search github for a similar issue or PR before submitting
- [ ] feature request

**Current behavior**

The package is working as intended on desktop but does not work as intended on mobile devices. I noted that scroll of any kind is totally disabled on mobile for all elements on the page when the lock is engaged. This unexpected behaviour can be observed when using the demo.

**Expected behavior**

On mobile devices the users expects that scroll would be be allowed on those elements that are not targeted and disabled on those that which is targeted.

**Reproduction of the problem**

The described bug behaviour is present in the demo version of this package at https://ngx-scroll-lock-sample.stackblitz.io/

**What is the motivation / use case for changing the behavior?**

The motivation for the change to the correct scroll-lock behaviour is so that users can employ the use of this package for mobile use. 

Android 10 / Chrome

- **Browser:** [Mobile Chrome ]

  

- **Language:** [ all ]

- **Node (if applicable):** `node --version` =

**Comment by willmendesneto** [comment]
Hi @louieogrady 👋 I'll check that over the weekend and share the updates on this issue.

Thanks for raising that!

**Comment by willmendesneto** [comment]
Hi @louieogrady . Thanks for raising this issue. That was fixed in [this commit](https://github.com/willmendesneto/ngx-scroll-lock/commit/5bbc06b74f0dede48dc0c79b0aee9c9c8a3fe8c2). Please update your project to use `ngx-scroll-lock@9.1.1`.

One more time, thanks for raise this issue!
